### ISSUE TITLE
Feature request.

### ISSUE THREAD

**Issue by V1EngineeringInc** [vector76/gcode_tpgen#1]
Would it be fairly easy for you to make a gcode generator for squaring tests? Like 4 "X"'s in each corner of a build with work area input?

If the user homed their machine first and started it at the surface, the starting Ccode would be the same between machines.

**Comment by V1EngineeringInc** [comment]
If that is possible and not a huge hassle let me know what something like that would run me. 
My backup plan is just to post the gcode and let users change a couple numbers to suit their builds.

**Comment by vector76** [comment]
That's super easy.  Would you want "X" shapes at some distance from the corner, or perhaps L shapes that mark each corner of a box?  Or maybe + shapes?  I assume this is for squaring.

**Comment by V1EngineeringInc** [comment]
Which ever is easiest. Yeah for squaring. L or + is fine

**Comment by vector76** [comment]
Ok, give it a look and see what you think.  I just simulated in ncviewer and I haven't tried it (but it's pretty simple).

It draws four 'L' shapes in a continuous counterclockwise loop, so I'm thinking it shouldn't be messed up if there is backlash.

I wouldn't want backlash to contaminate squareness measurements.  Especially for a new machine, it's possible that someone might be trying to square the frame before the backlash is adjusted out.

I think 'X' shapes would also be robust to backlash provided the strokes are always made in the same order and the same direction.  It's possible that "+" shapes might be skewed a bit left-to-right or top-to-bottom if the pen approaches from different directions.

**Comment by V1EngineeringInc** [comment]
I love it. I had a preview of it. I will run it tonight or tomorrow to double check it but it looks great so far.

I have some boxes to pack but I know If I start messing with it I will surely start tuning all my builds.

Thank you so much. Please send me an invoice for your time!

**Comment by V1EngineeringInc** [comment]
I tried to make a hose mounted belt holder and that is not accurate enough. Lots of flex there.

The code though, I think it would be best to start with a G92 X0 Y0 Z0. That way you can set the pen with the right pressure after you manually home X and Y. Then it is super newb friendly.

I need to figure out a different pen mount.

**Comment by vector76** [comment]
Sounds good.  There is already an option to start with G92 X0 Y0 Z0 and it is enabled by default, so I think this is covered.

I have some ideas for a pen holder I want to implement someday, but that's a separate conversation for another forum.

**Comment by V1EngineeringInc** [comment]
Well shoot I read that as G28. Thank you so very much!
